#[Info]
site_name: RXY's note #网站名字
site_url: #网站地址
site_author: RXY #作者名
#[UI]
theme:
  name: material
  palette:
    #primary: blue grey
  
    - scheme: default # 日间模式
      primary: white # 主色
      accent: cyan # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black 
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features: 
    - navigation.instant #- header.autohide  #自动隐藏
    #- announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    #- navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    #- navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - navigation.expand # 打开Tab时左侧目录全部展开
    #- navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - search.share #搜索分享按钮
  language: zh # 一些提示性的文字会变成中文
  
 
  icon: 
    repo: fontawesome/brands/github #右上角图标
edit_uri: edit/main/docs # 编辑按钮跳转的链接 
repo_url: https://github.com/RXY3/mkdoc-record_of_study#mkdoc-record_of_study # 右上角点击跳转的链接
repo_name: RXY3.github.io # 右上角的名字
 
# [Navigtion]
nav: 
  - 主页:
    - index.md
  - AI:
    - 机器学习:
      - AI/机器学习/机器学习基础.md
    - 深度学习:
      - AI/深度学习/深度学习基础.md
  - CorCpp:
    - C++:
      - CorCpp/C++/C++基础.md
      - C++刷题记录:
        - CorCpp/C++/C++刷题记录.md
    - C语言:
      - CorCpp/C语言/C语言基础.md
  - Python:
    - Python/Python基础.md
    - Python/Python进阶.md
  - Web:
    - HTML:
      - Web/HTML/HTML基础.md
    - CSS:
      - Web/CSS/CSS基础.md
    - JavaScript:
      - Web/JavaScript/JavaScript基础.md
  - ZJU_CS:
    - 数据结构基础:
      - ZJU_CS/数据结构基础.md
    - 数字逻辑设计:
      - ZJU_CS/数字逻辑设计.md
    - 计算机组成原理:
      - ZJU_CS/计算机组成原理.md
    - 面向对象程序设计:
      - ZJU_CS/面向对象程序设计.md
    - 高级数据结构:
      - ZJU_CS/高级数据结构.md
    - 数据库系统原理:
      - ZJU_CS/数据库系统原理.md
  - Missing_sem:
    - git:
      - Missing_sem/git.md
    - markdown:
      - Missing_sem/markdown.md
    - Bash:
      - Missing_sem/Bash.md
      

  
  
copyright: Copyright &copy; 2004-徐梓毓 # 左下角的版权声明
  
 
extra:
  generator: false  #删除页脚显示“使用 MkDocs 材料制造”
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RXY3
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1407028951?spm_id_from=333.1007.0.0
    - icon: fontawesome/solid/paper-plane
      link: mailto:<2787064294@qq.com> #联系方式
  
  analytics: 
    provider: google
    property: G-XXXXXXXXXX # Google Analytics ID
    feedback:
      title: 此页面有帮助吗？
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            谢谢你的反馈！
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.
  
  consent:
    title: Cookie consent
    description: >- 
      我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。
      如果你同意,你可以帮助我们让我们的网站更好
 
      

 
 
markdown_extensions:
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
     
     
extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
 
